package payment

const (
	METHODE_TYPE_CARD                 string = "CARD"
	METHODE_TYPE_CRYPTOCURRENCY       string = "CRYPTOCURRENCY"
	METHODE_TYPE_DIRECT_BANK_TRANSFER string = "DIRECT_BANK_TRANSFER"
	METHODE_TYPE_DIRECT_DEBIT         string = "DIRECT_DEBIT"
	METHODE_TYPE_EWALLET              string = "EWALLET"
	METHODE_TYPE_OVER_THE_COUNTER     string = "OVER_THE_COUNTER"
	METHODE_TYPE_QR_CODE              string = "QR_CODE"
	METHODE_TYPE_VIRTUAL_ACCOUNT      string = "VIRTUAL_ACCOUNT"
)
