// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Customer struct {
	Uid               string             `json:"uid"`
	CustomerAppID     string             `json:"customer_app_id"`
	PaymentCustomerID string             `json:"payment_customer_id"`
	CustomerName      string             `json:"customer_name"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Email             pgtype.Text        `json:"email"`
	PhoneNumber       pgtype.Text        `json:"phone_number"`
}

type PaymentChannel struct {
	Uid             string          `json:"uid"`
	Pcname          string          `json:"pcname"`
	PcType          string          `json:"pc_type"`
	LogoSrc         string          `json:"logo_src"`
	MinAmount       decimal.Decimal `json:"min_amount"`
	MaxAmount       decimal.Decimal `json:"max_amount"`
	Tax             decimal.Decimal `json:"tax"`
	IsTaxPercentage bool            `json:"is_tax_percentage"`
	IsActive        bool            `json:"is_active"`
	IsAvailable     bool            `json:"is_available"`
}

type PaymentMethod struct {
	Uid                string          `json:"uid"`
	PaymentMethodID    string          `json:"payment_method_id"`
	PaymentRequestID   pgtype.Text     `json:"payment_request_id"`
	PaymentReferenceID string          `json:"payment_reference_id"`
	PaymentBusinessID  string          `json:"payment_business_id"`
	PaymentCustomerID  string          `json:"payment_customer_id"`
	PaymentType        string          `json:"payment_type"`
	PaymentStatus      string          `json:"payment_status"`
	PaymentReusability string          `json:"payment_reusability"`
	PaymentChannel     string          `json:"payment_channel"`
	PaymentAmount      decimal.Decimal `json:"payment_amount"`
	// for QR_CODE payment type
	PaymentQrCode pgtype.Text `json:"payment_qr_code"`
	// for BANK payment type
	PaymentVirtualAccountNumber pgtype.Text `json:"payment_virtual_account_number"`
	// for EWALLET payment type
	PaymentUrl pgtype.Text `json:"payment_url"`
	// LIMIT Text Should not exceeding 100 chars
	PaymentDescription string `json:"payment_description"`
	// See here https://docs.xendit.co/id/subscriptions-payment-failure-code for reference
	PaymentFailureCode pgtype.Text        `json:"payment_failure_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	PaidAt             pgtype.Timestamptz `json:"paid_at"`
}

type PaymentReusability struct {
	Prname string `json:"prname"`
}

type PaymentStatus struct {
	Psname string `json:"psname"`
}

type PaymentType struct {
	Ptname string `json:"ptname"`
}
